Develop1
4e27c1/QA-java-diplom-1 pull request #1
Opened 2023-10-22 06:55 UTC by 4e27c1

Написаны тесты на классы Burger, Bun, Ingredient, IngredientType  
Добавлен отчет Jacoco о покрытии

2023-11-04 19:38 UTC, pavel-ulan requested changes
Неплохо, но assertation надо добавить

2023-11-04 19:38 UTC, pavel-ulan commented on src/test/java/praktikum/BurgerTest.java
> +        Mockito.verify(testBurger, atLeastOnce()).removeIngredient(1);
**надо исправить**
Смотри, verify это несомненно та же проверка и будет еще круче, если в итоге у нас будет задействован один из Assert методов. Это важно по многим причинам: отчеты вытягивают данные из репортов которые генерятся тестовым фреймворком, он в свою очередь смотрит на результаты assertations. Внешние тулы типа тесттрекинговых ориентируются на эти результаты. Да и в целом, это читается проще 
Так что добавь или замени проверку на соответствующие assertation

2023-11-05 13:58 UTC, 4e27c1 commented on src/test/java/praktikum/BurgerTest.java
> +        Mockito.verify(testBurger, atLeastOnce()).removeIngredient(1);
добавила ассерты

2023-11-06 21:59 UTC, pavel-ulan approved these changes
Валидно, молодец

2023-11-06 21:59 UTC, pavel-ulan commented on src/test/java/praktikum/BurgerTest.java
> +        Mockito.verify(testBurger, atLeastOnce()).removeIngredient(1);
Тогда уж стоило  Mockito.verify поставить перед Asserts. т.к. если они не пройдут, то и verify не тригернет

2023-11-07 12:45 UTC, 4e27c1 commented on src/test/java/praktikum/BurgerTest.java
> +        Mockito.verify(testBurger, atLeastOnce()).removeIngredient(1);
поменяла местами, чуть подправила ассерт

2023-11-07 12:47 UTC, merged